#!/bin/bash

echo "
# This file is generated by $0
---
conf:
  blacksmith-image: {{ blacksmith_variable "blacksmith-image" }}
  etcd: http://127.0.0.1:2379
  if: {{ machine_variable "internal_interface_name" }}
  cluster-name: {{ blacksmith_variable "cluster-name" }}
  lease-start: {{ blacksmith_variable "lease-start" }}
  lease-range: {{ blacksmith_variable "lease-range" }}
  dns: {{ blacksmith_variable "dns" }}
  file-server: {{ blacksmith_variable "file-server" }}
  http-listen: {{ .IP }}:8000
  api-listen: {{ .IP }}:8001
  workspace: /workspace
  workspace-repo: {{ blacksmith_variable "workspace-repo" }}
  workspace-repo-branch: {{ blacksmith_variable "workspace-repo-branch" }}
  initial-config: {{ blacksmith_variable "initial-config" }}
  private-key: {{ blacksmith_variable "private-key" }}
  debug: true
  agent-tls-cert: {{ blacksmith_variable "agent-tls-cert" }}
  agent-tls-key: {{ blacksmith_variable "agent-tls-key" }}
  agent-tls-ca: {{ blacksmith_variable "agent-tls-ca" }}
  tls-cert: {{ blacksmith_variable "tls-cert" }}
  tls-key: {{ blacksmith_variable "tls-key" }}
  tls-ca: {{ blacksmith_variable "tls-ca" }}
  agent-url: {{ blacksmith_variable "agent-url" }}
" > /var/lib/blacksmith/workspaces/blacksmith-config.yaml

docker run --name blacksmith --net=host \
  -v /var/lib/blacksmith/workspaces:/workspace \
  -v /var/lib/blacksmith/certs:/certs \
  -v /etc/ssl/certs:/etc/ssl/certs \
  {{ blacksmith_variable "blacksmith-image" }} --verbose --config /workspace/blacksmith-config.yaml
