#!/bin/bash

echo "
# This file is generated by $0
---
conf:
  blacksmith-image: {{ blacksmith_variable "blacksmith-image" }}
  workspace: /workspace
  etcd: http://127.0.0.1:2379
  if: $1
  cluster-name: {{ blacksmith_variable "cluster-name" }}
  lease-start: {{ blacksmith_variable "lease-start" }}
  lease-range: {{ blacksmith_variable "lease-range" }}
  dns: {{ blacksmith_variable "dns" }}
  file-server: {{ blacksmith_variable "file-server" }}
  http-listen: 127.0.0.1:8000
  api-listen: 127.0.0.1:8001
  workspace: /workspace
  workspace-repo: {{ blacksmith_variable "workspace-repo" }}
  workspace-config: /workspace/initial.yaml
  debug: true
  tls-cert: {{ blacksmith_variable "tls-cert" }}
  tls-key: {{ blacksmith_variable "tls-key" }}
  tls-ca: {{ blacksmith_variable "tls-ca" }}
  agent-url: {{ blacksmith_variable "agent-url" }}
" > /var/lib/blacksmith/workspaces/blacksmith-config.yaml

docker run --name blacksmith --net=host \
  -v /var/lib/blacksmith/workspaces:/workspace \
  -v /var/lib/blacksmith/certs:/certs \
  -v /etc/ssl/certs:/etc/ssl/certs \
  {{ blacksmith_variable "blacksmith-image" }} --verbose --config /workspace/blacksmith-config.yaml
