#!/bin/bash

SOCK=unix:///var/run/early-docker.sock
docker -H $SOCK rm -f blacksmith || true
docker -H $SOCK pull {{ blacksmith_variable "blacksmith-image" }}

echo "
# This file is generated by $0
---
conf:
  blacksmith-image: {{ blacksmith_variable "blacksmith-image" }}
  workspace: /workspace
  etcd: http://127.0.0.1:2379
  if: $1
  cluster-name: {{ blacksmith_variable "cluster-name" }}
  lease-start: {{ blacksmith_variable "lease-start" }}
  lease-range: {{ blacksmith_variable "lease-range" }}
  dns: {{ blacksmith_variable "dns" }}
  file-server: {{ blacksmith_variable "file-server" }}
  http-listen: 127.0.0.1:8000
  api-listen: 127.0.0.1:8001
  workspace: /workspace
  workspace-repo: {{ blacksmith_variable "workspace-repo" }}
  workspace-config: /workspace/initial.yaml
  tls-cert: /certs/server.crt
  tls-key: /certs/server.key
  tls-ca: /certs/ca.crt
  debug: true
" > /var/lib/blacksmith/workspaces/blacksmith-config.yaml

docker -H $SOCK run --name blacksmith --restart=always -d --net=host \
  -v /var/lib/blacksmith/workspaces:/workspace \
  -v /var/lib/blacksmith/certs:/certs \
  -v /etc/ssl/certs:/etc/ssl/certs \
  {{ blacksmith_variable "blacksmith-image" }} --verbose --config /workspace/blacksmith-config.yaml
