#!/bin/bash
set -x
source ./scripts/common.bash

cat << EOF
# This file is generated by $0
---
conf:
  blacksmith-image: ${BlacksmithImage}
  etcd: http://${BobIP}:2379
  if: ${Bridge1}
  cluster-name: cafecluster
  lease-start: ${LeaseStart}
  file-server: http://${BobIP}/
  lease-range: 10
  dns: 8.8.8.8
  debug: true
  http-listen: ${BobIP}:8000
  api-listen: ${BobIP}:8001
  tls-cert: $(base64 -w0 certs/server.crt)
  tls-key: $(base64 -w0 certs/server.key)
  tls-ca: $(base64 -w0 certs/ca.crt)
  agent-tls-cert: $(base64 -w0 certs/client.crt)
  agent-tls-key: $(base64 -w0 certs/client.key)
  agent-tls-ca: $(base64 -w0 certs/ca.crt)
  agent-url: http://${BobIP}/blacksmith-agent
  workspace: /workspace
  workspace-repo: ${WorkspaceGitURL}
  workspace-repo-branch: ${WorkspaceGitBranch}
  initial-config: /workspace/initial.yaml
  private-key: $(base64 -w0 ~/.ssh/id_rsa)
  insecure-registry: ${BobIP}:5000
ssh-keys:
  - $(cat ~/.ssh/id_rsa.pub)
EOF
